### ISSUE TITLE
Remove obsolete version tracking assertions in exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/erlang#278]
Some tracks have added assertions to the exercise test suites that ensure that the solution has a hard-coded version in it.
In the old version of the site, this was useful, as it let commenters see what version of the test suite the code had been written against, and they wouldn't accidentally tell people that their code was wrong, when really the world had just moved on since it was submitted.

If this track does not have any assertions that track versions in the exercise tests, please close this issue.

If this track _does_ have this bookkeeping code, then please remove it from all the exercises.

See https://github.com/exercism/exercism/issues/4266 for the full explanation of this change.

---

Checklist:

- [x] Prepare generator
  - [x] remove version tests
  - [x] generate a comment describing the exact commit the tests are generated from (or use the version from the JSON)
- [x] Regenerate tests **without** bumping canonical data
- [x] Remove version test test from manually maintained exercises
  - [x] Remove `example:test_version/0`s implementation and from export list of all examples
  - [x] Remove `Slug:test_version/0`s implementation and from export list of all exercises stub files
  - [x] Remove the assertion from the testsuites
- [x] Make sure no documents (READMEs, HINTs, etc) reference the `test_version/0` anymore.

**Comment by NobbZ** [comment]
I've updated the initial post with a checklist.
