### ISSUE TITLE
[v3] Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/erlang#452]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [ ] [Configure online editor](https://github.com/exercism/erlang/issues/443)
- [ ] [Add key features](https://github.com/exercism/erlang/issues/444)
- [ ] [Add tags](https://github.com/exercism/erlang/issues/445)
- [ ] [Add prerequisites to Practice Exercises](https://github.com/exercism/erlang/issues/446)
- [ ] [Update status of track](https://github.com/exercism/erlang/issues/450)
- [ ] [Update status of Concept Exercises](https://github.com/exercism/erlang/issues/451)
- [ ] [Pass linting checks](https://github.com/exercism/erlang/issues/447)
- [ ] [Build Test Runner](https://github.com/exercism/erlang/issues/448)
- [ ] [Build Analyzer and Representer](https://github.com/exercism/erlang/issues/449) (optional)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7
